# Generated by Django 6.0.6 on 2026-06-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_notification_acknowledged_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressupdate',
            name='can_edit',
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Designates whether the owner can purge this log.'),
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='can_update',
            field=models.BooleanField(default=True, help_text='Designates whether the owner can modify this log.'),
        ),
        migrations.AlterField(
            model_name='progressupdate',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='progressupdate',
            name='task_done',
            field=models.CharField(max_length=255),
        ),
    ]
